version: '3.8'

services:
  perseus-prod:
    container_name: perseus-prod
    image: ${DOCKER_USERNAME}/perseus:prod
    ports:
      - "8080:8080"
    env_file: .env.prod
    restart: always

  perseus-dev:
    container_name: perseus-dev
    image: ${DOCKER_USERNAME}/perseus:dev
    ports:
      - "8081:8080"
    env_file: .env.dev
    restart: always