spring:
  application:
    name: perseus

  profiles:
    default: dev

  lifecycle:
    timeout-per-shutdown-phase: 30s

  mail:
#    host: smtp.gmail.com
    host: email-smtp.ap-northeast-2.amazonaws.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

server:
  shutdown: graceful